---

- file: path="/data/sepal" state=directory
- file: path="/data/sepal/ldap" state=directory
- file: path="/data/sepal/certificates" state=directory
- copy: src=~/.sepal/certificates/ldap-ca.crt.pem dest=/data/sepal/certificates/ldap-ca.crt.pem

- name: Start container
  docker:
    docker_api_version: "1.16"
    name: "sepal"
    registry: "{{ docker_repository_host }}"
    pull: "{{ 'missing' if docker_repository_host == 'localhost'  else 'always' }}"
    image: "{{ docker_repository_host + '/' if docker_repository_host else '' }}openforis/sepal:{{ version }}"
    state: "reloaded"
    net: "bridge"
    restart_policy: "always"
    username: "{{ docker_username }}"
    email: "{{ docker_email }}"
    password: "{{ docker_password }}"
    links:
    - "mysql:mysql"
    volumes:
    - "/data/sepal:/data"
    - "/data/geoserver/layers:/geoserver"
    env:
      deploy_environment: "{{ deploy_environment }}"
      region: "{{ region }}"
      sepal_host: "{{ sepal_host }}"
      ldap_host: "{{ ldap_host }}"
      geoserver_password: "{{ geoserver_password }}"
      ldap_admin_password: "{{ ldap_admin_password }}"
      mysql_password: "{{ mysql_password }}"
      instances_config_file: "{{ '/etc/sepal/instances_local.yml' if use_custom_host == true else '/etc/sepal/instances.yml' }}"
      image_name: "{{ docker_repository_host + '/' if docker_repository_host else '' }}openforis/sandbox:{{ version }}"
      availability_zone: "{{ availability_zone }}"
      aws_access_key_id: "{{ aws_access_key_id }}"
      aws_secret_access_key: "{{ aws_secret_access_key }}"
      $USGS_PASSWORD_SEPAL_ENV: "{{ usgs_password }}"
