---
- file: path="/data/sepal" state=directory
- file: path="/data/sepal/ldap" state=directory
- file: path="/data/sepal/certificates" state=directory
- copy: src=~/.sepal/certificates/ldap-ca.crt.pem dest=/data/sepal/certificates/ldap-ca.crt.pem

- name: Start container
  docker:
    docker_api_version: "1.16"
    name: "sepal"
    registry: "{{ docker_repository_host }}"
    pull: "{{ 'missing' if docker_repository_host == 'localhost'  else 'always' }}"
    image: "{{ docker_repository_host + '/' if docker_repository_host else '' }}openforis/sepal:{{ version }}"
    state: "reloaded"
    net: "bridge"
    restart_policy: "always"
    username: "{{ docker_username }}"
    email: "{{ docker_email }}"
    password: "{{ docker_password }}"
    links:
    - "mysql:mysql"
    volumes:
    - "/data/sepal:/data"
    env:
      SEPAL_HOST_SEPAL_ENV: "{{ sepal_host }}"
      LDAP_HOST_SEPAL_ENV: "{{ ldap_host }}"
      LDAP_ADMIN_PASSWORD_SEPAL_ENV: "{{ ldap_admin_password }}"
      MYSQL_PASSWORD_SEPAL_ENV: "{{ mysql_password }}"
      USGS_PASSWORD_SEPAL_ENV: "{{ usgs_password }}"
      IMAGE_NAME_SEPAL_ENV: "{{ docker_repository_host + '/' if docker_repository_host else '' }}openforis/sandbox:{{ version }}"
      DEPLOY_ENVIRONMENT_SEPAL_ENV: "{{ deploy_environment }}"
      REGION_SEPAL_ENV: "{{ region }}"
      INSTANCES_CONFIG_FILE_SEPAL_ENV: "{{ '/etc/sepal/instances_local.yml' if use_custom_host == true else '/etc/sepal/instances.yml' }}"
      AVAILABILITY_ZONE_SEPAL_ENV: "{{ availability_zone }}"
      AWS_ACCESS_KEY_ID_SEPAL_ENV: "{{ aws_access_key_id }}"
      AWS_SECRET_ACCESS_KEY_SEPAL_ENV: "{{ aws_secret_access_key }}"
      SEPAL_WORKING_MODE_SEPAL_ENV: "{{ sepal_working_mode }}"
      SEPAL_VERSION_SEPAL_ENV: "{{ version }}"
