---

- name: Create user dir
  file:
    path: "/data/sepal/users"
    state: directory

- name: Create user home dir
  file:
    path: "/data/sepal/home"
    state: directory

- name: Create log dir
  file:
    path: "/data/logs/ssh-gateway"
    state: directory

- name: Start container
  docker:
    docker_api_version: 1.16
    name: ssh-gateway
    registry: "{{ docker_repository_host }}"
    pull: "{{ 'always' if docker_repository_host else 'missing' }}"
    image: "{{ docker_repository_host + '/' if docker_repository_host else '' }}openforis/ssh-gateway"
    state: started
    restart_policy: always
    username: "{{ docker_username }}"
    email: "{{ docker_email }}"
    password: "{{ docker_password }}"
    ports:
    - "2222:22"
    links:
    - "sepal:sepal"
    volumes:
    - /data/sepal/users:/users
    - /data/logs/ssh-gateway:/var/log/supervisor
    - /data/sepal/home:/home

