---

- name: "sepal | Install Maven"
  apt: name="maven"

- name: "sepal | Determine if jar should be built"
  script: "{{ module_dir }}/should-rebuild.sh"
  delegate_to: 127.0.0.1
  sudo: false
  register: should_rebuild
  changed_when: should_rebuild.stdout_lines[0] == 'true'

- name: "sepal | Build jar"
  shell: mvn clean package -DskipTests=true chdir="{{ module_dir }}"
  delegate_to: 127.0.0.1
  sudo: false
  when: should_rebuild.changed

- name: "sepal | Build"
  docker_image: path="/opt/sepal/modules/sepal-server/docker" name="localhost/openforis/sepal" state=build
