---

- name: "sepal | Install Maven"
  apt: name="maven"

- name: "sepal | Determine if binaries should be built"
  script: ../sepal-server/should-rebuild.sh
  delegate_to: 127.0.0.1
  sudo: false
  register: should_rebuild
  changed_when: should_rebuild.stdout_lines[0] == 'true'

- name: "sepal | Build binaries"
  shell: mvn clean package -DskipTests=true chdir="/opt/sepal/modules/sepal-server"
  when: should_rebuild.changed

- name: "sepal | Build"
  docker_image: path="/opt/sepal/modules/sepal-server/docker" name="localhost/openforis/sepal" state=build
