---

- name: Copy worker image pulling script
  template: src=pull_worker_images.sh dest=/data/sepal/pull_worker_images.sh mode=0777

- name: Pulling worker images
  shell: "/data/sepal/pull_worker_images.sh"
  register: sandbox_pull