---

- name: Copy the push script
  copy: src="push_images.sh" dest="/data/ansible/" mode="u=rwx,g=rx,o=rx"

- name: Copy the repo login script
  template: src=login_to_repo dest=/data/ansible/login_to_repo mode=0777

- name: Build mysql
  docker_image: path="/opt/sepal/docker/mysql" name="localhost/openforis/mysql" state=build

- name: Build jdk
  docker_image: path="/opt/sepal/docker/jdk" name="openforis/jdk" state=build

- name: Build geoserver
  docker_image: path="/opt/sepal/docker/geoserver" name="localhost/openforis/geoserver" state=build

- name: Build gateone
  docker_image: path="/opt/sepal/docker/gateone" name="localhost/openforis/gateone" state=build

- name: Build openforistoolkit
  docker_image: path="/opt/sepal/docker/openforistoolkit/oft-base" name="openforistoolkit" state=build

- name: Build openforistoolkit-gui-tools
  docker_image: path="/opt/sepal/docker/openforistoolkit/oft-gui-tools" name="openforistoolkit" tag="graphical-tools" state=build

- name: Build sandbox
  docker_image: path="/opt/sepal/docker/sandbox" name="localhost/openforis/sandbox" state=build

- name: Build sepal
  docker_image: path="/opt/sepal/docker/sepal" name="localhost/openforis/sepal" state=build nocache="{{ skip_cache }}"

- name: Build sepal-php
  docker_image: path="/opt/sepal/docker/sepal-php" name="localhost/openforis/sepal-php" state=build nocache="{{ skip_cache }}"

- name: Build nginx
  docker_image: path="/opt/sepal/docker/nginx" name="localhost/openforis/nginx" state=build

- name: Build ssh-gateway
  docker_image: path="/opt/sepal/docker/ssh-gateway" name="localhost/openforis/ssh-gateway" state=build

- name: Build jenkins
  docker_image: path="/opt/sepal/docker/jenkins" name="openforis/jenkins" state="build"

- name: Build haproxy
  docker_image: path="/opt/sepal/docker/haproxy" name="localhost/openforis/haproxy" state="build"

- name: Pushing the images to the local repo
  shell: "/data/ansible/login_to_repo"

