---
- name: Create geoserver user
  user: name=geoserver uid=998 group=sepal

- name: Create data dir
  file:
    path: "/data/sdms/geoserver"
    state: directory
    recurse: yes
    owner: geoserver
    group: sepal
    mode: 0770

- name: Create log dir
  file:
    path: "/data/logs/geoserver"
    state: directory
    owner: geoserver
    group: sepal

- name: Start container
  docker:
    docker_api_version: 1.16
    name: geoserver
    registry: "{{ docker_repository_host }}"
    pull: always
    image: "{{ docker_repository_host }}/openforis/geoserver"
    state: started
    restart_policy: always
    username: "{{ lookup('env','SEPAL_DOCKER_USERNAME') }}"
    email: "{{ lookup('env','SEPAL_DOCKER_EMAIL') }}"
    password: "{{ lookup('env','SEPAL_DOCKER_PASSWORD') }}"
    expose:
    - 80:80
    - 443:443
    volumes:
    - /data/sdms/geoserver:/data/geoserver
    - /data/logs/geoserver:/var/log/supervisor
    env:
      ADMIN_PASSWD: sdms
