---

- name: Create downloads dir
  file:
    path: "/data/sepal/downloads"
    owner: "sepal"
    group: "sepal"
    state: directory

- name: Create log dir
  file:
    path: "/data/logs/sepal"
    mode: "u=rwx,g=rx,o=rx"
    owner: "sepal"
    group: "sepal"
    state: directory

- name: Create config file
  template: src=sepal.properties dest=/data/sepal/config/sepal.properties owner=sepal group=sepal mode=0400

- name: Copy lsat_geoserver_script
  copy: src=lsat_geoserver_fix.sh dest=/data/sepal/config/processing_scripts/ owner=sepal group=sepal mode=u=rwx,g=r,o=r

- name: Start container
  docker:
    docker_api_version: "1.16"
    name: "sepal"
    registry: "{{ docker_repository_host }}"
    pull: "{{ 'always' if docker_repository_host else 'missing' }}"
    image: "{{ docker_repository_host + '/' if docker_repository_host else '' }}openforis/sepal:{{ version }}"
    state: "reloaded"
    net: "bridge"
    restart_policy: "always"
    username: "{{ docker_username }}"
    email: "{{ docker_email }}"
    password: "{{ docker_password }}"
    links:
    - "mysql:mysql"
    volumes:
    - "/data/sepal/downloads:/data/workDir/downloads"
    - "/data/sepal/config:/etc/sepal"
    - "/data/sepal/geoserver:/data/geoserver"
    - "/data/sepal/data:/data/home"
    - "/data/logs/sepal:/var/log/sepal"
    env:
    ARTIFACT_VERSION: "{{ version }-SNAPSHOT"
