---

#- name: "user | Install Maven"
#  apt: name="maven"

- name: "user | Determine if jar should be built"
  script: "{{ module_dir }}/should-rebuild.sh {{ module_dir }}"
  delegate_to: 127.0.0.1
  become: no
  register: should_rebuild
  changed_when: should_rebuild.stdout_lines[0] == 'true'

- name: "user | Build jar"
  shell: {{ module_dir }}/../../gradlew clean :sepal-user:build -x test"
#  shell: mvn clean package -DskipTests --projects modules/user --also-make chdir="{{ module_dir }}/../.."
  delegate_to: 127.0.0.1
  become: no
  when: should_rebuild.changed

- include_tasks: "{{ build_image_task }}"
