---
- name: Create data dir
  file:
    path: "/data/sdms/data"
    state: directory

- name: Create config dir
  file:
    path: "/data/sdms/config"
    state: directory

- name: Create log dir
  file:
    path: "/data/logs/sepal"
    state: directory

- name: Start container
  docker:
    docker_api_version: 1.16
    name: sepal
    registry: "{{ docker_repository_host }}"
    pull: always
    image: "{{ docker_repository_host }}/openforis/sepal"
    state: started
    restart_policy: always
    username: "{{ lookup('env','SEPAL_DOCKER_USERNAME') }}"
    email: "{{ lookup('env','SEPAL_DOCKER_EMAIL') }}"
    password: "{{ lookup('env','SEPAL_DOCKER_PASSWORD') }}"
    expose:
    - 1025:1025
    links:
    - "mysql:mysql"
    - "geoserver:geoserver"
    volumes:
    - /data/sdms/config:/etc/sdms
    - /data/sdms/geoserver:/data/geoserver
    - /data/logs/sepal:/var/log/sepal
    - /data/sdms/data:/data/home
