---
# common tasks

- name: Install Expect
  apt:
    name: "expect"

- name: Install nfs-common
  apt:
    name: "nfs-common"

- name: Create data dir
  file:
    path: "/data"
    state: "directory"
    mode: "u=rwx,g=rx"

- name: Create ssl certificates dir
  file:
    path: "/data/ssl/certificates"
    state: directory

- name: "Install Maven"
  apt:  name="maven"