- name: Configure Local Environment
  hosts: all
  user: vagrant
  sudo: yes
  gather_facts: true

  vars_files:
    - "{{ secret_vars_file }}"

  pre_tasks:
    - name: Create sepal group
      group: name=sepal state=present gid=9999
    - name: Add vagrant to sepal group
      user: name=vagrant append=yes groups=sepal
    - name: Create sepal user
      user: name=sepal uid=9999 group=sepal

    - name: Create docker-registry certificate dir
      file:
        path: "/etc/docker/certs.d/{{ docker_repository_host }}"
        state: directory
    - name: Copy docker-registry certificate
      copy:
        src: ~/.sepal/certificates/docker-registry.crt
        dest: "/etc/docker/certs.d/{{ docker_repository_host }}/ca.crt"

  roles:
    - role: unattended-upgrades
      unattended_origins_patterns:
        - 'origin=Ubuntu,archive=${distro_codename}-security'
        - 'o=Ubuntu,a=${distro_codename}-updates'

    - role: docker.ubuntu
      docker_version: '1.8.1-0~trusty'
      docker_storage_path: '/data/docker/'
      docker_group_members: ['ubuntu','vagrant']
      docker_opts: '-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock'

    - role: build-images
    - role: prepare-environment
    - role: mysql
    - role: geoserver
    - role: sepal
    - role: ssh-gateway
    - role: gateone
    - role: sepal-php
    - role: nginx
    - role: haproxy
    - role: sandbox