- name: Build Operations server
  hosts: all
  user: ubuntu
  sudo: yes
  gather_facts: true

  vars_files:
    - "{{ secret_vars_file }}"

  roles:
    - role: pull-images
    - role: build-images
    - role: tag-images
    - role: push-images


