- name: Build Operations server
  hosts: all
  user: vagrant
  sudo: yes
  gather_facts: true

  vars_files:
    - "{{ secret_vars_file }}"

  roles:
    - role: prepare-environment

    - role: docker.ubuntu
      docker_version: '1.8.1-0~trusty'
      docker_storage_path: '/data/docker/storage'
      docker_group_members: ['ubuntu','vagrant']
      docker_opts: '-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock'

    - role: docker-registry
    - role: build-images
    - role: ansible
    - role: jenkins

