- name: Build Operations server
  hosts: "tag_Type_Operations"
  user: ubuntu
  sudo: yes
  gather_facts: true

  vars_files:
    - "{{ secret_vars_file }}"

  roles:
    - role: prepare-environment

    - role: docker.ubuntu
      docker_version: '1.8.1-0~trusty'
      docker_group_members: ['ubuntu']
      docker_opts: '-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock -g /data/docker/storage'
    - role: docker-registry
    - role: pull-images
    - role: build-images
    - role: ansible
    - role: jenkins

