- name: Setup AWS
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
      - vars/vars.yml

  tasks:
    - name: Create Operations security group
      ec2_group:
        name: Operations
        description: The Sepal Security Group
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 168.202.0.0/16
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            from_port: 0
            to_port: 65535
            cidr_ip: 0.0.0.0/0

    - name: Provision Operations instance
      ec2:
        key_name: "{{ region }}"
        group: Operations
        instance_type: t2.medium
        image: "{{ ami_ids[region] }}"
        region: "{{ region }}"
        wait: true
        exact_count: 1
        count_tag:
          Type: Operations
        instance_tags:
          Name: "Operations"
          Type: Operations
        volumes:
          - device_name: /dev/sda1
            volume_size: 100
      register: ec2

    - name: Wait for SSH to be available in Sepal instance
      local_action: wait_for host="{{ item.public_ip }}"
                    port=22
                    state="started"
      with_items: ec2.instances
