---
- name: Create config dir
  file:
    path: "/data/haproxy"
    state: directory

- name: Create log dir
  file:
    path: "/data/logs/haproxy"
    state: directory

- name: Start container
  docker:
    docker_api_version: "1.16"
    name: "haproxy"
    registry: "{{ docker_repository_host }}"
    pull: "{{ 'missing' if docker_repository_host == 'localhost'  else 'always' }}"
    image: "{{ docker_repository_host + '/' if docker_repository_host else '' }}openforis/haproxy:{{ version }}"
    state: "reloaded"
    net: "bridge"
    restart_policy: "always"
    username: "{{ docker_username }}"
    email: "{{ docker_email }}"
    password: "{{ docker_password }}"
    ports:
    - "80:80"
    - "443:443"
    links:
    - "nginx:nginx"
    - "ssh-gateway:ssh-gateway"
    volumes:
    - "/data/haproxy:/data"
