- name: Create tmp directory
  file:
    path: "{{ module_dir }}/docker/build"
    state: directory

- name: Copy sepal lib
  copy:
    src: "{{ project_dir }}/lib"
    dest: "{{ module_dir }}/docker/build"

- include_tasks: "{{ build_image_task }}"
