---
- name: Create www-data user
  user: name=www-data uid=33 group=sepal

- name: Create data dir
  file:
    path: "/data/sepal/data"
    owner: "www-data"
    group: "sepal"
    mode: "u=rwx,g=rws"
    state: directory

- name: Create admin user dir
  file:
    path: "/data/sepal/data/sepalAdminWeb"
    state: directory
    owner: "1001"
    group: "sepal"

- name: Create admin user layers dir
  file:
    path: "/data/sepal/data/sepalAdminWeb/layers"
    state: directory

- name: Create admin user repo dir
  file:
    path: "/data/sepal/data/sepalAdminWeb/sdmsrepository"
    state: directory

- name: Create admin public repo
  file:
    path: "/data/sepal/public/sepalAdminWeb"
    state: directory
    owner: 1001

- name: Create symlink for admin public dir
  file:
    dest: "/data/sepal/data/sepalAdminWeb/public"
    src: "/data/sepal/public"
    state: "link"

- name: Create image dir
  file:
    path: "/data/sepal/images"
    owner: "www-data"
    group: "sepal"
    state: directory

- name: Create thumb dir
  file:
    path: "/data/sepal/images/thumbnail"
    owner: "www-data"
    group: "sepal"
    state: directory

- name: Create config dir
  file:
    path: "/data/sepal/config"
    state: directory

- name: Create public dir
  file:
    path: "/data/sepal/public"
    group: "9998"
    mode: "u=rwx,g=rs,o=r"
    state: directory

- name: Create admin public dir
  file:
    path: "/data/sepal/public/sepalAdminWeb"
    owner: "1001"
    group: "9998"
    state: directory




- name: Create config file
  template: src=config.ini dest=/data/sepal/config/config.ini owner=www-data mode=0400

- name: Create ssl certificates dir
  file:
    path: "/data/ssl/certificates"
    state: directory

- copy: src=~/.sepal/certificates/sepal-web-cert.key dest=/data/ssl/certificates/server.key
- copy: src=~/.sepal/certificates/fao-dm.ca-bundle dest=/data/ssl/certificates/fao-dm.ca-bundle
- copy: src=~/.sepal/certificates/fao-dm_org.crt dest=/data/ssl/certificates/fao-dm_org.crt

- name: Create log dir
  file:
    path: "/data/logs/sepal-php"
    state: directory

- name: Start container
  docker:
    docker_api_version: "1.16"
    name: "sepal-php"
    registry: "{{ docker_repository_host }}"
    pull: "{{ 'always' if docker_repository_host else 'missing' }}"
    image: "{{ docker_repository_host + '/' if docker_repository_host else '' }}openforis/sepal-php"
    state: "started"
    restart_policy: "always"
    username: "{{ docker_username }}"
    email: "{{ docker_email }}"
    password: "{{ docker_password }}"
    links:
    - "mysql:mysql"
    - "geoserver:geoserver"
    - "sepal:sepal"
    - "ssh-gateway:ssh-gateway"
    volumes:
    - "/data/logs/sepal-php:/var/log/apache2"
    - "/data/sepal/data:/data/home/"
    - "/data/sepal/config:/etc/sepal"
    - "/data/ssl/certificates:/etc/apache2/ssl"
    - "/data/sepal/images:/data/sdms-data-repo/scene-image"
    - "/data/sepal/public:/data/sepal/public"
    env:
        ADMIN_PWD: "{{ sepal_admin_user_password }}"
