---
- name: Create data dir
  file:
    path: "/data/sdms/data"
    state: directory

- name: Create config dir
  file:
    path: "/data/sdms/config"
    state: directory

- name: Create Apache config dir
  file:
    path: "/data/apache2/sites-enabled"
    state: directory

- name: Create ssl certificates dir
  file:
    path: "/data/ssl/certificates"
    state: directory

- name: Create log dir
  file:
    path: "/data/logs/sdms"
    state: directory

- name: Start container
  docker:
    docker_api_version: 1.16
    name: sepal-php
    registry: "{{ docker_repository_host }}"
    pull: always
    image: "{{ docker_repository_host }}/openforis/sepal-php"
    state: started
    restart_policy: always
    username: "{{ lookup('env','SEPAL_DOCKER_USERNAME') }}"
    email: "{{ lookup('env','SEPAL_DOCKER_EMAIL') }}"
    password: "{{ lookup('env','SEPAL_DOCKER_PASSWORD') }}"
    expose:
    - 80:80
    - 443:443
    links:
    - "mysql:mysql"
    - "geoserver:geoserver"
    - "sepal:sepal"
    volumes:
    - /data/sdms/data:/data/home/
    - /data/sdms/config:/etc/sdms
    - /data/apache2/sites-enabled:/etc/apache2/sites-enabled
    - /data/ssl/certificates:/etc/apache2/ssl
    - /data/logs/sdms:/var/log/supervisor
