- name: Create tmp directory
  file:
    path: "{{ module_dir }}/docker/.tmp"
    state: directory

- name: Copy sepal lib
  copy:
    src: "{{ project_dir }}/lib"
    dest: "{{ module_dir }}/docker/.tmp/"

- include_tasks: "{{ build_image_task }}"
  vars:
    image_name: "openforis/geospatial-toolkit"
