- name: "geospatial-toolkit | Create {{workspace}}modules/{{ module }}/docker/.build"
  file:
    path: "{{workspace}}modules/{{ module }}/docker/.build"
    recurse: yes


- name: 'geospatial-toolkit | Copy sepal-ee'
  synchronize:
    src: "{{ module_dir }}/../google-earth-engine/docker/sepal-ee"
    dest: "{{workspace}}modules/{{ module }}/docker/.build/"
    archive: yes
    recursive: yes
    delete: yes

- include_tasks: "{{ build_image_task }}"
  vars:
    image_name: "openforis/geospatial-toolkit"
