---
- name: Create config dir
  file:
    path: "/data/nginx/sites-enabled"
    state: directory

- name: Copy sepal config file
  copy: src=sepal dest=/data/nginx/sites-enabled/sepal


- copy: src=~/.sepal/certificates/sepal-https.key dest=/data/ssl/certificates/sepal-https.key
- copy: src=~/.sepal/certificates/sepal-https.ca-bundle dest=/data/ssl/certificates/sepal-https.ca-bundle
- copy: src=~/.sepal/certificates/sepal-https.crt dest=/data/ssl/certificates/sepal-https.crt

- name: Create log dir
  file:
    path: "/data/logs/nginx"
    state: directory

- name: Start container
  docker:
    docker_api_version: "1.16"
    name: "nginx"
    registry: "{{ docker_repository_host }}"
    pull: "{{ 'always' if docker_repository_host else 'missing' }}"
    image: "{{ docker_repository_host + '/' if docker_repository_host else '' }}openforis/nginx:{{ version }}"
    state: "reloaded"
    net: "bridge"
    restart_policy: "always"
    username: "{{ docker_username }}"
    email: "{{ docker_email }}"
    password: "{{ docker_password }}"
    links:
    - "gateone:gateone"
    - "sepal-php:sepal-php"
    - "geoserver:geoserver"
    - "sepal:sepal"
    volumes:
    - "/data/nginx/sites-enabled:/etc/nginx/sites-enabled"
    - "/data/ssl/certificates:/etc/ssl"
    - "/data/logs/nginx:/var/log/nginx"
