---
dependencies:
  - {
      role: docker.ubuntu,
      docker_version: '1.8.1-0~trusty',
      docker_group_members: '{{ users }}',
      docker_opts: '-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock -g /data/docker/storage --storage-opt dm.basesize=10G',
      pip_version_docker_py: '1.10.6',
      pip_version_docker_compose: '1.9.0'
  }
  # Using dm.basesize=10G to speed up container removal. See https://github.com/docker/docker/issues/18314
