- name: Build Operations server
  hosts: "tag_Type_Operations"
  user: ubuntu
  sudo: yes
  gather_facts: true

  vars_files:
    - "{{ secret_vars_file }}"

  pre_tasks:
    - name: Install Expect
      apt: name="expect"

    - name: Copy Jenkins Image
      copy: src="../../../modules/jenkins/" dest="/opt/sepal/modules/jenkins/"

  roles:
    - role: unattended-upgrades
      unattended_origins_patterns:
        - 'origin=Ubuntu,archive=${distro_codename}-security'
        - 'o=Ubuntu,a=${distro_codename}-updates'

    - { role: docker, users: ['ubuntu'] }
    - { role: docker-registry }
    - { role: ansible }
    - { role: build-image, image: jenkins }
    - { role: run-container, image: jenkins }

  post_tasks:
    - name: "Clean environment"
      shell: 'sudo rm -rf /opt/sepal'

    - name: "Create symlink to /opt/sepal"
      file:
        src: "/data/jenkins/workspace/Sepal"
        path: "/opt/sepal"
        state: "link"
        force: "yes"

