- name: Configure Local Environment
  hosts: all
  user: vagrant
  sudo: yes
  gather_facts: true

  vars_files:
    - vars/vars.yml
    - "{{ secret_vars_file }}"

  pre_tasks:
    - name: Create sepal group
      group: name=sepal state=present gid=9999
    - name: Add vagrant to sepal group
      user: name=vagrant append=yes groups=sepal
    - name: Create sepal user
      user: name=sepal uid=9999 group=sepal

    - name: Create docker-registry certificate dir
      file:
        path: "/etc/docker/certs.d/{{ docker_repository_host }}"
        state: directory
    - name: Copy docker-registry certificate
      copy:
        src: ~/.sepal/certificates/docker-registry.crt
        dest: "/etc/docker/certs.d/{{ docker_repository_host }}/ca.crt"

    - set_fact:
       sepal_host: "{{ custom_host if use_custom_host == true else inventory_hostname }}"
       region: "Localhost"
       aws_access_key_id: ""
       aws_secret_access_key: ""
       availability_zone: ""

  roles:
    - role: unattended-upgrades
      unattended_origins_patterns:
        - 'origin=Ubuntu,archive=${distro_codename}-security'
        - 'o=Ubuntu,a=${distro_codename}-updates'

    - role: docker.ubuntu
      docker_version: '1.8.1-0~trusty'
      docker_storage_path: '/data/docker/'
      docker_group_members: ['ubuntu','vagrant']
      docker_opts: '-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock'

    - role: prepare-environment
    - role: prepare-local-environment
    #- role: compile-binaries
    - role: build-haproxy
    - role: build-nginx
    - role: build-mysql
    - role: build-gateone
    - role: build-ssh-gateway
    - role: build-oft
    - role: build-sandbox
    - role: build-geoserver
    - role: build-sepal-php
    - role: build-sepal-server
    - role: run-mysql
    - role: run-geoserver
    - role: run-sepal-server
    - role: run-ssh-gateway
    - role: run-gateone
    - role: run-sepal-php
    - role: run-nginx
    - role: run-haproxy
