---
- name: Mount EFS Sepal Home Dir
  mount:
    name: "/data/sepal/home"
    fstype: "nfs4"
    state: "mounted"
    src: "{{ availability_zone }}.{{ efs_id }}.efs.{{ region }}.amazonaws.com:/data/sepal/home"

- name: Mount EFS Sepal Shiny Dir
  mount:
    name: "/data/sepal/shiny"
    fstype: "nfs4"
    state: "mounted"
    src: "{{ availability_zone }}.{{ efs_id }}.efs.{{ region }}.amazonaws.com:/data/sepal/shiny"

