---
- name: Mount EFS Sepal Home Dir
  mount:
    name: "/data/sepal/home"
    fstype: "efs"
    state: "mounted"
    src: "{{ efs_id }}:/data/sepal/home"
    opts: "defaults,_netdev"
    dump: 0
    passno: 0

- name: Mount EFS Sepal Shiny Dir
  mount:
    name: "/data/sepal/shiny"
    fstype: "efs"
    state: "mounted"
    src: "{{ efs_id }}:/data/sepal/shiny"
    opts: "defaults,_netdev"
    dump: 0
    passno: 0

