---
# common tasks

- name: Install nfs-common
  apt:
    name: "nfs-common"

- name: Create temp mount dir
  file:
    path: "/efs"
    state: "directory"

- name: Temporarily Mount Efs Nfs4 For Setting Up Folders
  mount:
    name: "/efs"
    fstype: "nfs4"
    state: "mounted"
    src: "{{ availability_zone }}.{{ efs_id }}.efs.{{ region }}.amazonaws.com:/"

- name: Create public dir
  file:
    path: "/efs/data/sepal/public"
    mode: "u=rwx,g=rxs,o=rx"
    state: directory

- name: Create data dir
  file:
    path: "/efs/data/sepal/home"
    owner: "9999"
    group: "9999"
    mode: "u=rwx,g=rwxs"
    state: "directory"

- name: Create ssh-gateway home dir
  file:
    path: "/efs/data/ssh-gateway/home"
    mode: "u=rwx,g=rxs,o=rx"
    state: directory

- name: Unmount Efs Nfs4
  mount:
      name: "/efs"
      fstype: "nfs4"
      state: "unmounted"
      src: "{{ availability_zone }}.{{ efs_id }}.efs.{{ region }}.amazonaws.com:/"

- name: Delete temp mount dir
  file:
      path: "/efs"
      state: "absent"

- name: Mount Efs Sepal Data Dir
  mount:
    name: "/data/sepal/home"
    fstype: "nfs4"
    state: "mounted"
    src: "{{ availability_zone }}.{{ efs_id }}.efs.{{ region }}.amazonaws.com:/data/sepal/home"

- name: Mount Efs Sepal Public Dir
  mount:
    name: "/data/sepal/public"
    fstype: "nfs4"
    state: "mounted"
    src: "{{ availability_zone }}.{{ efs_id }}.efs.{{ region }}.amazonaws.com:/data/sepal/public"

- name: Mount Efs Ssh-gateway Home Dir
  mount:
    name: "/data/ssh-gateway/home"
    fstype: "nfs4"
    state: "mounted"
    src: "{{ availability_zone }}.{{ efs_id }}.efs.{{ region }}.amazonaws.com:/data/ssh-gateway/home"
