- name: Build Operations server
  hosts: all
  user: vagrant
  sudo: yes
  gather_facts: true

  vars_files:
    - "{{ secret_vars_file }}"

  roles:
    - role: unattended-upgrades
      unattended_origins_patterns:
        - 'origin=Ubuntu,archive=${distro_codename}-security'
        - 'o=Ubuntu,a=${distro_codename}-updates'

    - role: docker.ubuntu
      docker_version: '1.8.1-0~trusty'
      docker_group_members: ['ubuntu','vagrant']
      docker_opts: '-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock -g /data/docker/storage'
     
    - role: docker-registry
    - role: ansible


    - { role: build-image, image: jenkins}
    - { role: run-container, image: jenkins}

