- name: config-generator
  hosts: all
  user: vagrant
  become: yes
  gather_facts: true

  tasks:
    - debug: msg='Provisioning config-generator'

    - name: Install OpenSSL
      apt: name="openssl"

    - name: Copy config generation scripts
      copy: src=./src/ dest=/usr/local/lib/sepal-config-generator/