---

- name: Start container
  docker:
    docker_api_version: "1.16"
    name: "mysql"
    pull: "missing"
    image: "openforis/mysql"
    state: "reloaded"
    restart_policy: "always"
    net: "bridge"

    ports:
      - "3306:3306"
    env:
      MYSQL_DATABASE: "sdms"
      MYSQL_USER: "sepal"
      MYSQL_PASSWORD: "sepal"
      MYSQL_ROOT_PASSWORD: "root"
