- name: Configure Sepal instance
  hosts: "tag_Type_Sepal:&tag_Environment_{{ deploy_environment }}"
  user: ubuntu
  become: yes
  gather_facts: true

  vars_files:
    - "{{ secret_vars_file }}"

  pre_tasks:
    - name: Create docker-registry certificate dir
      file:
        path: "/etc/docker/certs.d/{{ docker_repository_host }}"
        state: directory
    - name: Copy docker-registry certificate
      copy:
        src: "{{ config_home }}/certificates/docker-registry.crt"
        dest: "/etc/docker/certs.d/{{ docker_repository_host }}/ca.crt"
    - set_fact:
        ldap_host: "{{ ec2_private_ip_address }}"
        elk_host: "{{ elk_host }}"
        syslog_host: "172.17.0.1"
        syslog_address: "tcp://172.17.0.1:514"

    - file: path="/data/docker/storage/devicemapper/metadata" state=directory
    - file: path="/data/docker/storage/tmp" state=directory

    - file: path="/data/sepal/etc" state=directory
    - template: src="./aws.properties" dest=/data/sepal/etc/aws.properties

  roles:
    - role: unattended-upgrades
      unattended_origins_patterns:
        - 'origin=Ubuntu,archive=${distro_codename}-security'
        - 'o=Ubuntu,a=${distro_codename}-updates'
    - { role: rsyslog }
    - { role: docker, users: ['ubuntu'] }
    - { role: aws-mount-efs }
    - { role: run-module, module: ldap }
    - { role: run-module, module: ldap-backup }
    - { role: run-module, module: mysql }
    - { role: run-module, module: mysql-backup }
    - { role: run-module, module: google-earth-engine}
    - { role: run-module, module: user }
    - { role: run-module, module: sepal-server }
    - { role: run-module, module: ssh-gateway }
    - { role: run-module, module: gateone }
    - { role: run-module, module: api-gateway }
    - { role: run-module, module: haproxy }
    - { role: run-module, module: letsencrypt }
