
- name: Configure EC2 instances
  hosts: tag_Name_Sepal
  user: ubuntu
  sudo: yes
  gather_facts: true

  tasks:
#  TODO: Is this actually needed? Try without
    - name: Gather EC2 facts
      action: ec2_facts

    - name: redis container
      docker:
        docker_api_version: 1.16
        name: redis
        image: redis
        command: redis-server --appendonly yes
        state: started
        expose:
        - 6379
        volumes:
        - /mydata

  roles:
    - role: unattended-upgrades
      unattended_origins_patterns:
      - 'origin=Ubuntu,archive=${distro_codename}-security'
      - 'o=Ubuntu,a=${distro_codename}-updates'

    - role: docker.ubuntu
      docker_version: '1.8.1-0~trusty'
      docker_storage_path: '/data/docker/'
      docker_group_members: ['ubuntu']