- name: Setup AWS
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create Sepal security group
      ec2_group:
        name: Sepal
        description: The Sepal Security Group
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 168.202.0.0/16
        rules_egress:
          - proto: all
            from_port: 0
            to_port: 65535
            cidr_ip: 0.0.0.0/0

    - name: Provision a set of instances
      ec2:
         key_name: test_key_pair
         group: Sepal
         instance_type: t2.micro
         image: "{{ ami_id }}"
         region: "{{ region }}"
         wait: true
         exact_count: 2
         count_tag:
            Name: Sepal
         instance_tags:
            Name: Sepal
            Environment: production
      register: ec2

    - name: Wait for SSH to be available
      local_action: wait_for host="{{ item.public_ip }}"
                    port=22
                    state="started"
      with_items: ec2.instances