---

- name: Copy .sepal folder
  copy: src=~/.sepal dest=~/

- name: Copy .ssh folder
  copy: src=~/.ssh/sepal dest=~/.ssh/


- name: Start jenkins container
  docker:
    docker_api_version: "1.18"
    name: "jenkins"
    pull: 'missing'
    image: "openforis/jenkins"
    state: "reloaded"
    net: "bridge"
    restart_policy: "always"
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - "/data/jenkins:/var/jenkins_home"
      - "/data/ansible/.sepal:/root/.sepal"
      - "/data/ansible/.ssh:/root/.ssh/sepal"
    env:
      JENKINS_PASSWD: "{{ jenkins_password }}"
      AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
      GITHUB_ACCOUNT_PASSWD: "{{ jenkins_github_user_password }}"
