- name: Build Operations server
  hosts: all
  user: vagrant
  become: yes
  gather_facts: true

  vars_files:
    - "{{ secret_vars_file }}"

  roles:
    - { role: docker-registry }
    - { role: ansible }

    - { role: build-module, module: jenkins }
    - { role: build-module, module: nginx }

    - { role: run-module, module: jenkins }
