- name: Build Operations server
  hosts: all
  user: vagrant
  become: yes
  gather_facts: true

  vars_files:
    - "{{ secret_vars_file }}"

  pre_tasks:
    - name: Install Expect
      apt: name="expect"

  roles:
    - role: unattended-upgrades
      unattended_origins_patterns:
        - 'origin=Ubuntu,archive=${distro_codename}-security'
        - 'o=Ubuntu,a=${distro_codename}-updates'

    - { role: docker, users: ['ubuntu', 'vagrant'] }
    - { role: docker-registry }
    - { role: ansible }
    - { role: build-image, image: jenkins }
    - { role: run-container, image: jenkins }
