- name: Build Operations server
  hosts: all
  user: vagrant
  become: yes
  gather_facts: true

  vars_files:
    - "{{ secret_vars_file }}"

  pre_tasks:

    - name: Create ELK certificate dir
      file:
        path: "/data/elk/certificates"
        state: directory
    - name: Copy ELK certificates
      copy: src={{ item }} dest=/data/elk/certificates owner=root mode=644
      with_fileglob:
        - ~/.sepal/certificates/elk*      

  roles:
    - role: unattended-upgrades
      unattended_origins_patterns:
        - 'origin=Ubuntu,archive=${distro_codename}-security'
        - 'o=Ubuntu,a=${distro_codename}-updates'

    - { role: docker, users: ['ubuntu', 'vagrant'] }
    - { role: docker-registry }
    - { role: ansible }

    - { role: build-module, module: jenkins }
    - { role: build-module, module: elk }
    - { role: build-module, module: nginx }
    - { role: build-module, module: riemann-server }
    - { role: build-module, module: riemann-dash }

    - { role: run-module, module: jenkins }
    - { role: run-module, module: elk }
    - { role: run-module, module: nginx }
    - { role: run-module, module: riemann-server }
    - { role: run-module, module: riemann-dash }
