---


- name: Create www-data user
  user: name=www-data uid=33 group=sepal

- name: Create admin user dir
  file:
    path: "/data/sepal/data/sepalAdminWeb"
    state: directory
    owner: "1001"
    group: "sepal"

- name: Create admin user layers dir
  file:
    path: "/data/sepal/data/sepalAdminWeb/layers"
    owner: "1001"
    mode: "u=rwx,g=rwxs"
    state: directory

- name: Create admin user repo dir
  file:
    path: "/data/sepal/data/sepalAdminWeb/sdmsrepository"
    owner: "1001"
    mode: "u=rwx,g=rwx"
    state: directory

- name: Create admin public repo
  file:
    path: "/data/sepal/public/sepalAdminWeb"
    state: directory
    owner: 1001

- name: Create symlink for admin public dir
  file:
    dest: "/data/sepal/data/sepalAdminWeb/public"
    src: "/data/sepal/public"
    state: "link"

- name: Create image dir
  file:
    path: "/data/sepal/images"
    owner: "www-data"
    group: "sepal"
    state: directory

- name: Create thumb dir
  file:
    path: "/data/sepal/images/thumbnail"
    owner: "www-data"
    group: "sepal"
    state: directory

- name: Create public dir
  file:
    path: "/data/sepal/public"
    group: "9998"
    mode: "u=rwx,g=rxs,o=rx"
    state: directory

- name: Create admin public dir
  file:
    path: "/data/sepal/public/sepalAdminWeb"
    owner: "1001"
    group: "9998"
    state: directory

- name: Create config file
  template: src=config.ini dest=/data/sepal/config/config.ini owner=www-data mode=0400

- copy: src=~/.sepal/certificates/sepal-https.key dest=/data/ssl/certificates/sepal-https.key
- copy: src=~/.sepal/certificates/sepal-https.ca-bundle dest=/data/ssl/certificates/sepal-https.ca-bundle
- copy: src=~/.sepal/certificates/sepal-https.crt dest=/data/ssl/certificates/sepal-https.crt

- name: Create log dir
  file:
    path: "/data/logs/sepal-php"
    state: directory

- name: Start container
  docker:
    docker_api_version: "1.16"
    name: "sepal-php"
    registry: "{{ docker_repository_host }}"
    pull: "{{ 'missing' if docker_repository_host == 'localhost'  else 'always' }}"
    image: "{{ docker_repository_host + '/' if docker_repository_host else '' }}openforis/sepal-php:{{ version }}"
    state: "reloaded"
    net: "bridge"
    restart_policy: "always"
    username: "{{ docker_username }}"
    email: "{{ docker_email }}"
    password: "{{ docker_password }}"
    links:
    - "mysql:mysql"
    - "geoserver:geoserver"
    - "sepal:sepal"
    - "ssh-gateway:ssh-gateway"
    volumes:
    #- "{{ '/www/app/controllers:/var/www/html/app/controllers' if local_php else '' }}"
    #- "{{ '/www/app/views:/var/www/html/app/views' if local_php else '' }}"
    #- "{{ '/www/app/config:/var/www/html/app/config' if local_php else '' }}"
    #- "{{ '/www/public:/var/www/html/public' if local_php else '' }}"
    - "/data/logs/sepal-php:/var/log/apache2"
    - "/data/sepal/data:/data/home/"
    - "/data/sepal/config:/etc/sepal"
    - "/data/ssl/certificates:/etc/apache2/ssl"
    - "/data/sepal/images:/data/sdms-data-repo/scene-image"
    - "/data/sepal/public:/data/sepal/public"
    env:
        ADMIN_PWD: "{{ sepal_admin_user_password }}"
        ARTIFACT_VERSION: "{{ version }}"
        ARTIFACT_SUFFIX: "-SNAPSHOT"
