- name: Build Operations server
  hosts: "tag_Type_Operations"
  user: ubuntu
  sudo: yes
  gather_facts: true

  vars_files:
    - "{{ secret_vars_file }}"

  pre_tasks:
    - name: Install Expect
      apt: name="expect"
    - name: Copy Jenkins Image
      copy: src="../../../modules/jenkins/" dest="/opt/sepal/modules/jenkins/"

  roles:
    - role: unattended-upgrades
      unattended_origins_patterns:
        - 'origin=Ubuntu,archive=${distro_codename}-security'
        - 'o=Ubuntu,a=${distro_codename}-updates'

    - role: docker.ubuntu
      docker_version: '1.8.1-0~trusty'
      docker_group_members: ['ubuntu']
      docker_opts: '-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock -g /data/docker/storage'

    - role: docker-registry
    - role: ansible
    - { role: build-image, image: jenkins}
    - { role: run-container, image: jenkins}

  post_tasks:
    - name: "Clean environment"
      file:
        path: "/opt/sepal/"
        state: "absent"

    - name: "Create symlink to /opt/sepal"
      file:
        src: "/data/jenkins/workspace/Sepal"
        path: "/opt/sepal"
        state: "link"
        force: "yes"

